export const LOAD_USERLIST_SUCCESS = 'USERLIST/LOAD_USERLIST_SUCCESS';

export const LOAD_USER_PROFILE = 'USER_PROFILE/LOAD_USER_PROFILE';
export const LOAD_USER_PROFILE_SUCCESS = 'USER_PROFILE/LOAD_USER_PROFILE_SUCCESS';
